//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildCompanyWPF.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adress
    {
        public string Id { get; set; }
        public string Number { get; set; }
        public string City { get; set; }
        public string Adress1 { get; set; }
    }
}
